# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_windows_security_context_options import IoK8sApiCoreV1WindowsSecurityContextOptions

class TestIoK8sApiCoreV1WindowsSecurityContextOptions(unittest.TestCase):
    """IoK8sApiCoreV1WindowsSecurityContextOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1WindowsSecurityContextOptions:
        """Test IoK8sApiCoreV1WindowsSecurityContextOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1WindowsSecurityContextOptions`
        """
        model = IoK8sApiCoreV1WindowsSecurityContextOptions()
        if include_optional:
            return IoK8sApiCoreV1WindowsSecurityContextOptions(
                gmsa_credential_spec = '',
                gmsa_credential_spec_name = '',
                host_process = True,
                run_as_user_name = ''
            )
        else:
            return IoK8sApiCoreV1WindowsSecurityContextOptions(
        )
        """

    def testIoK8sApiCoreV1WindowsSecurityContextOptions(self):
        """Test IoK8sApiCoreV1WindowsSecurityContextOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
