# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_volume_mount import IoK8sApiCoreV1VolumeMount

class TestIoK8sApiCoreV1VolumeMount(unittest.TestCase):
    """IoK8sApiCoreV1VolumeMount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1VolumeMount:
        """Test IoK8sApiCoreV1VolumeMount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1VolumeMount`
        """
        model = IoK8sApiCoreV1VolumeMount()
        if include_optional:
            return IoK8sApiCoreV1VolumeMount(
                mount_path = '',
                mount_propagation = '',
                name = '',
                read_only = True,
                recursive_read_only = '',
                sub_path = '',
                sub_path_expr = ''
            )
        else:
            return IoK8sApiCoreV1VolumeMount(
                mount_path = '',
                name = '',
        )
        """

    def testIoK8sApiCoreV1VolumeMount(self):
        """Test IoK8sApiCoreV1VolumeMount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
