# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.jobset_v1alpha2_job_set_scheduling import JobsetV1alpha2JobSetScheduling

class TestJobsetV1alpha2JobSetScheduling(unittest.TestCase):
    """JobsetV1alpha2JobSetScheduling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobsetV1alpha2JobSetScheduling:
        """Test JobsetV1alpha2JobSetScheduling
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobsetV1alpha2JobSetScheduling`
        """
        model = JobsetV1alpha2JobSetScheduling()
        if include_optional:
            return JobsetV1alpha2JobSetScheduling(
                constraints = jobset.models.io/k8s/api/scheduling/v1alpha3/pod_group_scheduling_constraints.io.k8s.api.scheduling.v1alpha3.PodGroupSchedulingConstraints(
                    topology = [
                        jobset.models.io/k8s/api/scheduling/v1alpha3/topology_constraint.io.k8s.api.scheduling.v1alpha3.TopologyConstraint(
                            key = '', )
                        ], ),
                disruption = jobset.models.io/k8s/api/scheduling/v1alpha3/disruption_mode.io.k8s.api.scheduling.v1alpha3.DisruptionMode(
                    all = jobset.models.io/k8s/api/scheduling/v1alpha3/all_disruption_mode.io.k8s.api.scheduling.v1alpha3.AllDisruptionMode(), 
                    single = jobset.models.io/k8s/api/scheduling/v1alpha3/single_disruption_mode.io.k8s.api.scheduling.v1alpha3.SingleDisruptionMode(), ),
                policy = jobset.models.io/k8s/api/scheduling/v1alpha3/pod_group_scheduling_policy.io.k8s.api.scheduling.v1alpha3.PodGroupSchedulingPolicy(
                    basic = jobset.models.io/k8s/api/scheduling/v1alpha3/basic_scheduling_policy.io.k8s.api.scheduling.v1alpha3.BasicSchedulingPolicy(), 
                    gang = jobset.models.io/k8s/api/scheduling/v1alpha3/gang_scheduling_policy.io.k8s.api.scheduling.v1alpha3.GangSchedulingPolicy(
                        min_count = 56, ), ),
                replicated_job_policies = [
                    jobset.models.jobset_v1alpha2_replicated_job_scheduling_policy.JobsetV1alpha2ReplicatedJobSchedulingPolicy(
                        constraints = jobset.models.io/k8s/api/scheduling/v1alpha3/pod_group_scheduling_constraints.io.k8s.api.scheduling.v1alpha3.PodGroupSchedulingConstraints(
                            topology = [
                                jobset.models.io/k8s/api/scheduling/v1alpha3/topology_constraint.io.k8s.api.scheduling.v1alpha3.TopologyConstraint(
                                    key = '', )
                                ], ), 
                        disruption = jobset.models.io/k8s/api/scheduling/v1alpha3/disruption_mode.io.k8s.api.scheduling.v1alpha3.DisruptionMode(
                            all = jobset.models.io/k8s/api/scheduling/v1alpha3/all_disruption_mode.io.k8s.api.scheduling.v1alpha3.AllDisruptionMode(), 
                            single = jobset.models.io/k8s/api/scheduling/v1alpha3/single_disruption_mode.io.k8s.api.scheduling.v1alpha3.SingleDisruptionMode(), ), 
                        policy = jobset.models.io/k8s/api/scheduling/v1alpha3/pod_group_scheduling_policy.io.k8s.api.scheduling.v1alpha3.PodGroupSchedulingPolicy(
                            basic = jobset.models.io/k8s/api/scheduling/v1alpha3/basic_scheduling_policy.io.k8s.api.scheduling.v1alpha3.BasicSchedulingPolicy(), 
                            gang = jobset.models.io/k8s/api/scheduling/v1alpha3/gang_scheduling_policy.io.k8s.api.scheduling.v1alpha3.GangSchedulingPolicy(
                                min_count = 56, ), ), 
                        resource_claims = [
                            jobset.models.io/k8s/api/scheduling/v1alpha3/pod_group_resource_claim.io.k8s.api.scheduling.v1alpha3.PodGroupResourceClaim(
                                name = '', 
                                resource_claim_name = '', 
                                resource_claim_template_name = '', )
                            ], 
                        target_replicated_job = '', )
                    ]
            )
        else:
            return JobsetV1alpha2JobSetScheduling(
        )
        """

    def testJobsetV1alpha2JobSetScheduling(self):
        """Test JobsetV1alpha2JobSetScheduling"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
