# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_key_to_path import IoK8sApiCoreV1KeyToPath

class TestIoK8sApiCoreV1KeyToPath(unittest.TestCase):
    """IoK8sApiCoreV1KeyToPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1KeyToPath:
        """Test IoK8sApiCoreV1KeyToPath
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1KeyToPath`
        """
        model = IoK8sApiCoreV1KeyToPath()
        if include_optional:
            return IoK8sApiCoreV1KeyToPath(
                key = '',
                mode = 56,
                path = ''
            )
        else:
            return IoK8sApiCoreV1KeyToPath(
                key = '',
                path = '',
        )
        """

    def testIoK8sApiCoreV1KeyToPath(self):
        """Test IoK8sApiCoreV1KeyToPath"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
