# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints

class TestIoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints:
        """Test IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints`
        """
        model = IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints()
        if include_optional:
            return IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints(
                topology = [
                    jobset.models.io/k8s/api/scheduling/v1alpha3/topology_constraint.io.k8s.api.scheduling.v1alpha3.TopologyConstraint(
                        key = '', )
                    ]
            )
        else:
            return IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints(
        )
        """

    def testIoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints(self):
        """Test IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
