# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_pod_certificate_projection import IoK8sApiCoreV1PodCertificateProjection

class TestIoK8sApiCoreV1PodCertificateProjection(unittest.TestCase):
    """IoK8sApiCoreV1PodCertificateProjection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1PodCertificateProjection:
        """Test IoK8sApiCoreV1PodCertificateProjection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1PodCertificateProjection`
        """
        model = IoK8sApiCoreV1PodCertificateProjection()
        if include_optional:
            return IoK8sApiCoreV1PodCertificateProjection(
                certificate_chain_path = '',
                credential_bundle_path = '',
                key_path = '',
                key_type = '',
                max_expiration_seconds = 56,
                signer_name = ''
            )
        else:
            return IoK8sApiCoreV1PodCertificateProjection(
                key_type = '',
                signer_name = '',
        )
        """

    def testIoK8sApiCoreV1PodCertificateProjection(self):
        """Test IoK8sApiCoreV1PodCertificateProjection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
