# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha3_workload_composite_pod_group_disruption_mode import IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode

class TestIoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode:
        """Test IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode`
        """
        model = IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode()
        if include_optional:
            return IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode(
                all = None,
                single = None
            )
        else:
            return IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode(
        )
        """

    def testIoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode(self):
        """Test IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
