# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_topology_spread_constraint import IoK8sApiCoreV1TopologySpreadConstraint

class TestIoK8sApiCoreV1TopologySpreadConstraint(unittest.TestCase):
    """IoK8sApiCoreV1TopologySpreadConstraint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1TopologySpreadConstraint:
        """Test IoK8sApiCoreV1TopologySpreadConstraint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1TopologySpreadConstraint`
        """
        model = IoK8sApiCoreV1TopologySpreadConstraint()
        if include_optional:
            return IoK8sApiCoreV1TopologySpreadConstraint(
                label_selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                    match_expressions = [
                        jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ),
                match_label_keys = [
                    ''
                    ],
                max_skew = 56,
                min_domains = 56,
                node_affinity_policy = '',
                node_taints_policy = '',
                topology_key = '',
                when_unsatisfiable = ''
            )
        else:
            return IoK8sApiCoreV1TopologySpreadConstraint(
                max_skew = 56,
                topology_key = '',
                when_unsatisfiable = '',
        )
        """

    def testIoK8sApiCoreV1TopologySpreadConstraint(self):
        """Test IoK8sApiCoreV1TopologySpreadConstraint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
