# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_downward_api_volume_file import IoK8sApiCoreV1DownwardAPIVolumeFile

class TestIoK8sApiCoreV1DownwardAPIVolumeFile(unittest.TestCase):
    """IoK8sApiCoreV1DownwardAPIVolumeFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1DownwardAPIVolumeFile:
        """Test IoK8sApiCoreV1DownwardAPIVolumeFile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1DownwardAPIVolumeFile`
        """
        model = IoK8sApiCoreV1DownwardAPIVolumeFile()
        if include_optional:
            return IoK8sApiCoreV1DownwardAPIVolumeFile(
                field_ref = jobset.models.io/k8s/api/core/v1/object_field_selector.io.k8s.api.core.v1.ObjectFieldSelector(
                    api_version = '', 
                    field_path = '', ),
                mode = 56,
                path = '',
                resource_field_ref = jobset.models.io/k8s/api/core/v1/resource_field_selector.io.k8s.api.core.v1.ResourceFieldSelector(
                    container_name = '', 
                    divisor = '', 
                    resource = '', )
            )
        else:
            return IoK8sApiCoreV1DownwardAPIVolumeFile(
                path = '',
        )
        """

    def testIoK8sApiCoreV1DownwardAPIVolumeFile(self):
        """Test IoK8sApiCoreV1DownwardAPIVolumeFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
