# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.jobset_v1alpha2_failure_policy import JobsetV1alpha2FailurePolicy

class TestJobsetV1alpha2FailurePolicy(unittest.TestCase):
    """JobsetV1alpha2FailurePolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobsetV1alpha2FailurePolicy:
        """Test JobsetV1alpha2FailurePolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobsetV1alpha2FailurePolicy`
        """
        model = JobsetV1alpha2FailurePolicy()
        if include_optional:
            return JobsetV1alpha2FailurePolicy(
                max_restarts = 56,
                restart_strategy = '',
                rules = [
                    jobset.models.jobset_v1alpha2_failure_policy_rule.JobsetV1alpha2FailurePolicyRule(
                        action = '', 
                        name = '', 
                        on_job_failure_reasons = [
                            ''
                            ], 
                        target_replicated_jobs = [
                            ''
                            ], )
                    ]
            )
        else:
            return JobsetV1alpha2FailurePolicy(
        )
        """

    def testJobsetV1alpha2FailurePolicy(self):
        """Test JobsetV1alpha2FailurePolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
