# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.jobset_v1alpha2_replicated_job_scheduling import JobsetV1alpha2ReplicatedJobScheduling

class TestJobsetV1alpha2ReplicatedJobScheduling(unittest.TestCase):
    """JobsetV1alpha2ReplicatedJobScheduling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobsetV1alpha2ReplicatedJobScheduling:
        """Test JobsetV1alpha2ReplicatedJobScheduling
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobsetV1alpha2ReplicatedJobScheduling`
        """
        model = JobsetV1alpha2ReplicatedJobScheduling()
        if include_optional:
            return JobsetV1alpha2ReplicatedJobScheduling(
                disruption_mode = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_composite_pod_group_disruption_mode.io.k8s.api.scheduling.v1alpha3.WorkloadCompositePodGroupDisruptionMode(
                    all = jobset.models.all.all(), 
                    single = jobset.models.single.single(), ),
                job = jobset.models.jobset_v1alpha2_job_scheduling.JobsetV1alpha2JobScheduling(
                    disruption_mode = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_disruption_mode.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupDisruptionMode(
                        all = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_all_disruption_mode.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupAllDisruptionMode(), 
                        single = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_single_disruption_mode.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupSingleDisruptionMode(), ), 
                    resource_claims = [
                        jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_resource_claim.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupResourceClaim(
                            name = '', 
                            resource_claim_name = '', 
                            resource_claim_template_name = '', )
                        ], 
                    scheduling_constraints = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_scheduling_constraints.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupSchedulingConstraints(
                        topology = [
                            jobset.models.io/k8s/api/scheduling/v1alpha3/topology_constraint.io.k8s.api.scheduling.v1alpha3.TopologyConstraint(
                                key = '', )
                            ], ), 
                    scheduling_policy = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_scheduling_policy.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupSchedulingPolicy(
                        basic = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_basic_scheduling_policy.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupBasicSchedulingPolicy(), 
                        gang = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_gang_scheduling_policy.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupGangSchedulingPolicy(
                            min_count = 56, ), ), ),
                scheduling_constraints = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_composite_pod_group_scheduling_constraints.io.k8s.api.scheduling.v1alpha3.WorkloadCompositePodGroupSchedulingConstraints(
                    topology = [
                        jobset.models.io/k8s/api/scheduling/v1alpha3/topology_constraint.io.k8s.api.scheduling.v1alpha3.TopologyConstraint(
                            key = '', )
                        ], ),
                scheduling_policy = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_composite_pod_group_scheduling_policy.io.k8s.api.scheduling.v1alpha3.WorkloadCompositePodGroupSchedulingPolicy(
                    basic = jobset.models.basic.basic(), 
                    gang = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_composite_pod_group_gang_scheduling_policy.io.k8s.api.scheduling.v1alpha3.WorkloadCompositePodGroupGangSchedulingPolicy(
                        min_group_count = 1, ), ),
                target_replicated_jobs = [
                    ''
                    ]
            )
        else:
            return JobsetV1alpha2ReplicatedJobScheduling(
                target_replicated_jobs = [
                    ''
                    ],
        )
        """

    def testJobsetV1alpha2ReplicatedJobScheduling(self):
        """Test JobsetV1alpha2ReplicatedJobScheduling"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
