# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_apimachinery_pkg_apis_meta_v1_list_meta import IoK8sApimachineryPkgApisMetaV1ListMeta

class TestIoK8sApimachineryPkgApisMetaV1ListMeta(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1ListMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApimachineryPkgApisMetaV1ListMeta:
        """Test IoK8sApimachineryPkgApisMetaV1ListMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApimachineryPkgApisMetaV1ListMeta`
        """
        model = IoK8sApimachineryPkgApisMetaV1ListMeta()
        if include_optional:
            return IoK8sApimachineryPkgApisMetaV1ListMeta(
                var_continue = '',
                remaining_item_count = 56,
                resource_version = '',
                self_link = ''
            )
        else:
            return IoK8sApimachineryPkgApisMetaV1ListMeta(
        )
        """

    def testIoK8sApimachineryPkgApisMetaV1ListMeta(self):
        """Test IoK8sApimachineryPkgApisMetaV1ListMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
