# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_container_restart_rule import IoK8sApiCoreV1ContainerRestartRule

class TestIoK8sApiCoreV1ContainerRestartRule(unittest.TestCase):
    """IoK8sApiCoreV1ContainerRestartRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1ContainerRestartRule:
        """Test IoK8sApiCoreV1ContainerRestartRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1ContainerRestartRule`
        """
        model = IoK8sApiCoreV1ContainerRestartRule()
        if include_optional:
            return IoK8sApiCoreV1ContainerRestartRule(
                action = '',
                exit_codes = jobset.models.io/k8s/api/core/v1/container_restart_rule_on_exit_codes.io.k8s.api.core.v1.ContainerRestartRuleOnExitCodes(
                    operator = '', 
                    values = [
                        56
                        ], )
            )
        else:
            return IoK8sApiCoreV1ContainerRestartRule(
                action = '',
        )
        """

    def testIoK8sApiCoreV1ContainerRestartRule(self):
        """Test IoK8sApiCoreV1ContainerRestartRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
