# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha3_disruption_mode import IoK8sApiSchedulingV1alpha3DisruptionMode

class TestIoK8sApiSchedulingV1alpha3DisruptionMode(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha3DisruptionMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha3DisruptionMode:
        """Test IoK8sApiSchedulingV1alpha3DisruptionMode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha3DisruptionMode`
        """
        model = IoK8sApiSchedulingV1alpha3DisruptionMode()
        if include_optional:
            return IoK8sApiSchedulingV1alpha3DisruptionMode(
                all = jobset.models.io/k8s/api/scheduling/v1alpha3/all_disruption_mode.io.k8s.api.scheduling.v1alpha3.AllDisruptionMode(),
                single = jobset.models.io/k8s/api/scheduling/v1alpha3/single_disruption_mode.io.k8s.api.scheduling.v1alpha3.SingleDisruptionMode()
            )
        else:
            return IoK8sApiSchedulingV1alpha3DisruptionMode(
        )
        """

    def testIoK8sApiSchedulingV1alpha3DisruptionMode(self):
        """Test IoK8sApiSchedulingV1alpha3DisruptionMode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
