# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha1_workload_spec import IoK8sApiSchedulingV1alpha1WorkloadSpec

class TestIoK8sApiSchedulingV1alpha1WorkloadSpec(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha1WorkloadSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha1WorkloadSpec:
        """Test IoK8sApiSchedulingV1alpha1WorkloadSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha1WorkloadSpec`
        """
        model = IoK8sApiSchedulingV1alpha1WorkloadSpec()
        if include_optional:
            return IoK8sApiSchedulingV1alpha1WorkloadSpec(
                controller_ref = jobset.models.io/k8s/api/scheduling/v1alpha1/typed_local_object_reference.io.k8s.api.scheduling.v1alpha1.TypedLocalObjectReference(
                    api_group = '', 
                    kind = '', 
                    name = '', ),
                pod_groups = [
                    jobset.models.io/k8s/api/scheduling/v1alpha1/pod_group.io.k8s.api.scheduling.v1alpha1.PodGroup(
                        name = '', 
                        policy = jobset.models.io/k8s/api/scheduling/v1alpha1/pod_group_policy.io.k8s.api.scheduling.v1alpha1.PodGroupPolicy(
                            basic = jobset.models.io/k8s/api/scheduling/v1alpha1/basic_scheduling_policy.io.k8s.api.scheduling.v1alpha1.BasicSchedulingPolicy(), 
                            gang = jobset.models.io/k8s/api/scheduling/v1alpha1/gang_scheduling_policy.io.k8s.api.scheduling.v1alpha1.GangSchedulingPolicy(
                                min_count = 56, ), ), )
                    ]
            )
        else:
            return IoK8sApiSchedulingV1alpha1WorkloadSpec(
                pod_groups = [
                    jobset.models.io/k8s/api/scheduling/v1alpha1/pod_group.io.k8s.api.scheduling.v1alpha1.PodGroup(
                        name = '', 
                        policy = jobset.models.io/k8s/api/scheduling/v1alpha1/pod_group_policy.io.k8s.api.scheduling.v1alpha1.PodGroupPolicy(
                            basic = jobset.models.io/k8s/api/scheduling/v1alpha1/basic_scheduling_policy.io.k8s.api.scheduling.v1alpha1.BasicSchedulingPolicy(), 
                            gang = jobset.models.io/k8s/api/scheduling/v1alpha1/gang_scheduling_policy.io.k8s.api.scheduling.v1alpha1.GangSchedulingPolicy(
                                min_count = 56, ), ), )
                    ],
        )
        """

    def testIoK8sApiSchedulingV1alpha1WorkloadSpec(self):
        """Test IoK8sApiSchedulingV1alpha1WorkloadSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
