# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha3_workload_pod_group_disruption_mode import IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode

class TestIoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode:
        """Test IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode`
        """
        model = IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode()
        if include_optional:
            return IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode(
                all = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_all_disruption_mode.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupAllDisruptionMode(),
                single = jobset.models.io/k8s/api/scheduling/v1alpha3/workload_pod_group_single_disruption_mode.io.k8s.api.scheduling.v1alpha3.WorkloadPodGroupSingleDisruptionMode()
            )
        else:
            return IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode(
        )
        """

    def testIoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode(self):
        """Test IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
