# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_csi_volume_source import IoK8sApiCoreV1CSIVolumeSource

class TestIoK8sApiCoreV1CSIVolumeSource(unittest.TestCase):
    """IoK8sApiCoreV1CSIVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1CSIVolumeSource:
        """Test IoK8sApiCoreV1CSIVolumeSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1CSIVolumeSource`
        """
        model = IoK8sApiCoreV1CSIVolumeSource()
        if include_optional:
            return IoK8sApiCoreV1CSIVolumeSource(
                driver = '',
                fs_type = '',
                node_publish_secret_ref = jobset.models.io/k8s/api/core/v1/local_object_reference.io.k8s.api.core.v1.LocalObjectReference(
                    name = '', ),
                read_only = True,
                volume_attributes = {
                    'key' : ''
                    }
            )
        else:
            return IoK8sApiCoreV1CSIVolumeSource(
                driver = '',
        )
        """

    def testIoK8sApiCoreV1CSIVolumeSource(self):
        """Test IoK8sApiCoreV1CSIVolumeSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
