# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_core_v1_iscsi_volume_source import IoK8sApiCoreV1ISCSIVolumeSource

class TestIoK8sApiCoreV1ISCSIVolumeSource(unittest.TestCase):
    """IoK8sApiCoreV1ISCSIVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1ISCSIVolumeSource:
        """Test IoK8sApiCoreV1ISCSIVolumeSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1ISCSIVolumeSource`
        """
        model = IoK8sApiCoreV1ISCSIVolumeSource()
        if include_optional:
            return IoK8sApiCoreV1ISCSIVolumeSource(
                chap_auth_discovery = True,
                chap_auth_session = True,
                fs_type = '',
                initiator_name = '',
                iqn = '',
                iscsi_interface = '',
                lun = 56,
                portals = [
                    ''
                    ],
                read_only = True,
                secret_ref = jobset.models.io/k8s/api/core/v1/local_object_reference.io.k8s.api.core.v1.LocalObjectReference(
                    name = '', ),
                target_portal = ''
            )
        else:
            return IoK8sApiCoreV1ISCSIVolumeSource(
                iqn = '',
                lun = 56,
                target_portal = '',
        )
        """

    def testIoK8sApiCoreV1ISCSIVolumeSource(self):
        """Test IoK8sApiCoreV1ISCSIVolumeSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
