# permissions for the manager to access secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: manager-secrets-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/part-of: jobset
    app.kubernetes.io/managed-by: kustomize
  name: manager-secrets-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch