# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

# Settings related to issues
issues:
  # Which dirs to exclude: issues from them won't be reported
  exclude-dirs:
    - bin

# Settings of specific linters
linters-settings:
  goimports:
    local-prefixes: sigs.k8s.io/jobset

# Settings for enabling and disabling linters
linters:
  enable:
    - goimports
    - unparam
