apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: js
  annotations:
    # Not necessary, but likely useful
    # Example of value: cloud.google.com/gke-nodepool
    alpha.jobset.sigs.k8s.io/exclusive-topology: <CHANGE ME>
spec:
  failurePolicy:
    maxRestarts: 3
    restartStrategy: InPlaceRestart
  replicatedJobs:
  # This example uses 4 Pods in total
  - name: rj
    replicas: 2
    template:
      spec:
        completions: 2
        parallelism: 2
        backoffLimit: 2147483647
        podReplacementPolicy: Failed
        template:
          spec:
            # See examples/in-place-restart/service-account-example.yaml
            serviceAccountName: jobset-in-place-restart
            # Not necessary, but useful for testing
            terminationGracePeriodSeconds: 0
            containers:
            - name: in-place-restart-agent
              image: <CHANGE ME>
              env:
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              # Worker command that exits with the exit code of the file /tmp/exit[0-9]* when it is created
              - name: WORKER_COMMAND
                value: |
                  echo "Start"
                  while sleep 1; do
                    set -- /tmp/exit[0-9]*
                    [ -f "$1" ] && {
                      n=${1##*exit}
                      echo "exiting $n"
                      exit "$n"
                    }
                  done