# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobset-in-place-restart
  namespace: default
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobset-in-place-restart
  namespace: default
rules:
# Pod patcher
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
# JobSet watcher
- apiGroups: ["jobset.x-k8s.io"]
  resources: ["jobsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobset-in-place-restart
  namespace: default
subjects:
- kind: ServiceAccount
  name: jobset-in-place-restart
  namespace: default
roleRef:
  kind: Role
  name: jobset-in-place-restart
  apiGroup: rbac.authorization.k8s.io
---
# Validation admission policy
# Allow only the pod annotation "jobset.sigs.k8s.io/in-place-restart-attempt" to be updated
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: jobset-in-place-restart
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["UPDATE"]
      resources:   ["pods"]
  matchConditions:
  - name: is-target-service-account
    # Alternatively, you can use "request.userInfo.username.matches('^system:serviceaccount:[^:]+:jobset-in-place-restart$')" if you want the VAP to work for all service accounts named "jobset-in-place-restart" in all namespaces
    expression: "request.userInfo.username == 'system:serviceaccount:default:jobset-in-place-restart'"
  variables:
  # Alias and safe access
  - name: oldSpec
    expression: "object.spec"
  - name: newSpec
    expression: "oldObject.spec"
  - name: oldLabels
    expression: "has(oldObject.metadata.labels) ? oldObject.metadata.labels : {}"
  - name: newLabels
    expression: "has(object.metadata.labels) ? object.metadata.labels : {}"
  - name: oldAnnotations
    expression: "has(oldObject.metadata.annotations) ? oldObject.metadata.annotations : {}"
  - name: newAnnotations
    expression: "has(object.metadata.annotations) ? object.metadata.annotations : {}"
  # Check for unchanged fields
  - name: isSpecUnchanged
    expression: "variables.oldSpec == variables.newSpec"
  - name: isLabelsUnchanged
    expression: "variables.oldLabels == variables.newLabels"
  - name: isAnnotationsUnchangedExceptForInPlaceRestartAttempt
    expression: >
      variables.oldAnnotations.all(key, key == 'jobset.sigs.k8s.io/in-place-restart-attempt' || (key in variables.newAnnotations && variables.oldAnnotations[key] == variables.newAnnotations[key])) &&
      variables.newAnnotations.all(key, key == 'jobset.sigs.k8s.io/in-place-restart-attempt' || (key in variables.oldAnnotations && variables.oldAnnotations[key] == variables.newAnnotations[key]))
  validations:
  - expression: >
      variables.isSpecUnchanged &&
      variables.isLabelsUnchanged &&
      variables.isAnnotationsUnchangedExceptForInPlaceRestartAttempt
    message: "ServiceAccount 'jobset-in-place-restart' can only update the Pod annotation 'jobset.sigs.k8s.io/in-place-restart-attempt'."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: jobset-in-place-restart
spec:
  policyName: jobset-in-place-restart
  validationActions: [Deny]