{{- if and .Values.webhook.enabled .Values.certManager.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "jobset.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "jobset.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "jobset.fullname" . }}-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "jobset.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-jobset-x-k8s-io-v1alpha2-jobset
  failurePolicy: {{ .Values.webhook.mutatingWebhook.failurePolicy }}
  timeoutSeconds: {{ .Values.webhook.mutatingWebhook.timeoutSeconds }}
  name: mjobset.kb.io
  rules:
  - apiGroups:
    - jobset.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "jobset.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate--v1-pod
  failurePolicy: {{ .Values.webhook.mutatingWebhook.failurePolicy }}
  timeoutSeconds: {{ .Values.webhook.mutatingWebhook.timeoutSeconds }}
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
{{- end }}

