{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobset.fullname" . }}-webhook-service
  labels:
    {{- include "jobset.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "jobset.selectorLabels" . | nindent 4 }}
{{- end }}
