apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-jobset
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-jobset-role
  namespace: argo
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - jobset.x-k8s.io
    resources:
      - jobsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - jobset.x-k8s.io
    resources:
      - jobsets/finalizers
    verbs:
      - update
  - apiGroups:
      - jobset.x-k8s.io
    resources:
      - jobsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-jobset-binding
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-jobset-role
subjects:
  - kind: ServiceAccount
    name: argo-jobset
    namespace: argo