apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: exclusive-placement
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool # 1:1 job replica to node pool assignment
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: workers
    replicas: 3 # set to number of node pools
    template:
      spec:
        parallelism: 3
        completions: 3
        backoffLimit: 10
        template:
          spec:
            containers:
            - name: sleep
              image: busybox
              command: 
                - sleep
              args:
                - 1000s
