apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: failure-policy
spec:
  failurePolicy:
    # Wait for all Jobs to be fully deleted before recreating any.
    # Defaults to "Recreate" which restarts Jobs individually.
    restartStrategy: BlockingRecreate
    # On failure, restart all jobs up to 3 times.
    maxRestarts: 3
  replicatedJobs:
  - name: leader
    replicas: 1
    template:
      spec:
        # Set backoff limit to 0 so job will immediately fail if any pod fails.
        backoffLimit: 0 
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: leader
              image: bash:latest
              # Default failure policy is to recreate all jobs if any jobs fails. 
              # The bash script provides a simple demonstration of it by failing
              # the pod with completion index 0, which will trigger job failure
              # and the jobset controller wil recreate all jobs. 
              command:
              - bash
              - -xc
              - |
                echo "JOB_COMPLETION_INDEX=$JOB_COMPLETION_INDEX"
                if [[ "$JOB_COMPLETION_INDEX" == "0" ]]; then
                  for i in $(seq 10 -1 1)
                  do
                    echo "Sleeping in $i"
                    sleep 1
                  done
                  exit 1
                fi
                for i in $(seq 1 1000)
                do
                  echo "$i"
                  sleep 1
                done
  - name: workers
    replicas: 1
    template:
      spec:
        backoffLimit: 0 
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: worker
              image: bash:latest
              command:
              - bash
              - -xc
              - |
                sleep 1000