/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	jobsetv1alpha2 "sigs.k8s.io/jobset/api/jobset/v1alpha2"
	applyconfigurationjobsetv1alpha2 "sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2"
	scheme "sigs.k8s.io/jobset/client-go/clientset/versioned/scheme"
)

// JobSetsGetter has a method to return a JobSetInterface.
// A group's client should implement this interface.
type JobSetsGetter interface {
	JobSets(namespace string) JobSetInterface
}

// JobSetInterface has methods to work with JobSet resources.
type JobSetInterface interface {
	Create(ctx context.Context, jobSet *jobsetv1alpha2.JobSet, opts v1.CreateOptions) (*jobsetv1alpha2.JobSet, error)
	Update(ctx context.Context, jobSet *jobsetv1alpha2.JobSet, opts v1.UpdateOptions) (*jobsetv1alpha2.JobSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, jobSet *jobsetv1alpha2.JobSet, opts v1.UpdateOptions) (*jobsetv1alpha2.JobSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*jobsetv1alpha2.JobSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*jobsetv1alpha2.JobSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *jobsetv1alpha2.JobSet, err error)
	Apply(ctx context.Context, jobSet *applyconfigurationjobsetv1alpha2.JobSetApplyConfiguration, opts v1.ApplyOptions) (result *jobsetv1alpha2.JobSet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, jobSet *applyconfigurationjobsetv1alpha2.JobSetApplyConfiguration, opts v1.ApplyOptions) (result *jobsetv1alpha2.JobSet, err error)
	JobSetExpansion
}

// jobSets implements JobSetInterface
type jobSets struct {
	*gentype.ClientWithListAndApply[*jobsetv1alpha2.JobSet, *jobsetv1alpha2.JobSetList, *applyconfigurationjobsetv1alpha2.JobSetApplyConfiguration]
}

// newJobSets returns a JobSets
func newJobSets(c *JobsetV1alpha2Client, namespace string) *jobSets {
	return &jobSets{
		gentype.NewClientWithListAndApply[*jobsetv1alpha2.JobSet, *jobsetv1alpha2.JobSetList, *applyconfigurationjobsetv1alpha2.JobSetApplyConfiguration](
			"jobsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *jobsetv1alpha2.JobSet { return &jobsetv1alpha2.JobSet{} },
			func() *jobsetv1alpha2.JobSetList { return &jobsetv1alpha2.JobSetList{} },
		),
	}
}
