/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// JobSetStatusApplyConfiguration represents a declarative configuration of the JobSetStatus type for use
// with apply.
//
// JobSetStatus defines the observed state of JobSet
type JobSetStatusApplyConfiguration struct {
	// conditions track status
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// restarts tracks the number of times the JobSet has globally restarted (i.e. recreated all Jobs due to a restart action such as RestartJobSet).
	// That is, it tracks how many times the restart actions RestartJobSet and RestartJobSetAndIgnoreMaxRestarts were executed.
	Restarts *int32 `json:"restarts,omitempty"`
	// restartsCountTowardsMax tracks the number of times the JobSet has globally restarted that counts towards the maximum allowed number of restarts (i.e. recreated all Jobs due to a restart action such as RestartJobSet).
	// That is, it tracks how many times the restart action RestartJobSet was executed.
	RestartsCountTowardsMax *int32 `json:"restartsCountTowardsMax,omitempty"`
	// totalRestarts tracks the number of times the JobSet has restarted in any way (e.g., this also counts restart actions such as RestartJob).
	// This will be set to Restarts if not specified.
	TotalRestarts *int32 `json:"totalRestarts,omitempty"`
	// totalRestartsCountTowardsMax tracks the number of times the JobSet has restarted in any way that counts towards the maximum allowed number of restarts (e.g., this also counts restart actions such as RestartJob).
	// This will be set to RestartsCountTowardsMax if not specified.
	TotalRestartsCountTowardsMax *int32 `json:"totalRestartsCountTowardsMax,omitempty"`
	// terminalState tracks the state of the JobSet when it finishes execution.
	// It can be either Completed or Failed. Otherwise, it is empty by default.
	TerminalState *string `json:"terminalState,omitempty"`
	// replicatedJobsStatus tracks the number of JobsReady for each replicatedJob.
	ReplicatedJobsStatus []ReplicatedJobStatusApplyConfiguration `json:"replicatedJobsStatus,omitempty"`
	// previousInPlaceRestartAttempt tracks the previous in-place restart attempt
	// of the JobSet. It is read by the agent. If the in-place restart
	// attempt of the Pod is smaller than or equal to previousInPlaceRestartAttempt,
	// the agent should restart its Pod in-place.
	PreviousInPlaceRestartAttempt *int32 `json:"previousInPlaceRestartAttempt,omitempty"`
	// currentInPlaceRestartAttempt tracks the current in-place restart attempt
	// of the JobSet. It is read by the agent. If the in-place restart
	// attempt of the Pod is equal to currentInPlaceRestartAttempt, the agent
	// should lift its barrier to allow the worker container to
	// start running.
	CurrentInPlaceRestartAttempt *int32 `json:"currentInPlaceRestartAttempt,omitempty"`
}

// JobSetStatusApplyConfiguration constructs a declarative configuration of the JobSetStatus type for use with
// apply.
func JobSetStatus() *JobSetStatusApplyConfiguration {
	return &JobSetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *JobSetStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *JobSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithRestarts sets the Restarts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Restarts field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithRestarts(value int32) *JobSetStatusApplyConfiguration {
	b.Restarts = &value
	return b
}

// WithRestartsCountTowardsMax sets the RestartsCountTowardsMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartsCountTowardsMax field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithRestartsCountTowardsMax(value int32) *JobSetStatusApplyConfiguration {
	b.RestartsCountTowardsMax = &value
	return b
}

// WithTotalRestarts sets the TotalRestarts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalRestarts field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithTotalRestarts(value int32) *JobSetStatusApplyConfiguration {
	b.TotalRestarts = &value
	return b
}

// WithTotalRestartsCountTowardsMax sets the TotalRestartsCountTowardsMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalRestartsCountTowardsMax field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithTotalRestartsCountTowardsMax(value int32) *JobSetStatusApplyConfiguration {
	b.TotalRestartsCountTowardsMax = &value
	return b
}

// WithTerminalState sets the TerminalState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminalState field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithTerminalState(value string) *JobSetStatusApplyConfiguration {
	b.TerminalState = &value
	return b
}

// WithReplicatedJobsStatus adds the given value to the ReplicatedJobsStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReplicatedJobsStatus field.
func (b *JobSetStatusApplyConfiguration) WithReplicatedJobsStatus(values ...*ReplicatedJobStatusApplyConfiguration) *JobSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReplicatedJobsStatus")
		}
		b.ReplicatedJobsStatus = append(b.ReplicatedJobsStatus, *values[i])
	}
	return b
}

// WithPreviousInPlaceRestartAttempt sets the PreviousInPlaceRestartAttempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreviousInPlaceRestartAttempt field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithPreviousInPlaceRestartAttempt(value int32) *JobSetStatusApplyConfiguration {
	b.PreviousInPlaceRestartAttempt = &value
	return b
}

// WithCurrentInPlaceRestartAttempt sets the CurrentInPlaceRestartAttempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentInPlaceRestartAttempt field is set to the value of the last call.
func (b *JobSetStatusApplyConfiguration) WithCurrentInPlaceRestartAttempt(value int32) *JobSetStatusApplyConfiguration {
	b.CurrentInPlaceRestartAttempt = &value
	return b
}
