/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha3 "k8s.io/api/scheduling/v1alpha3"
)

// ReplicatedJobSchedulingPolicyApplyConfiguration represents a declarative configuration of the ReplicatedJobSchedulingPolicy type for use
// with apply.
//
// ReplicatedJobSchedulingPolicy targets one or more named ReplicatedJobs with
// leaf-level scheduling configuration.
type ReplicatedJobSchedulingPolicyApplyConfiguration struct {
	// targetReplicatedJob is the list of ReplicatedJob names this policy applies to.
	// When more than one name is listed, the targeted ReplicatedJobs share a single
	// PodGroup. Every name must be unique across all replicatedJobPolicies entries.
	TargetReplicatedJob []string `json:"targetReplicatedJob,omitempty"`
	// schedulingPolicy defines the leaf-level scheduling policy (basic or gang) for
	// jobs created by the targeted ReplicatedJobs.
	// Defaults to Gang when not specified.
	SchedulingPolicy *v1alpha3.PodGroupSchedulingPolicy `json:"schedulingPolicy,omitempty"`
	// schedulingConstraints defines leaf-level topology constraints for the targeted
	// ReplicatedJobs' pods.
	SchedulingConstraints *v1alpha3.PodGroupSchedulingConstraints `json:"schedulingConstraints,omitempty"`
	// disruptionMode defines how pods within the targeted ReplicatedJobs can be disrupted.
	DisruptionMode *v1alpha3.DisruptionMode `json:"disruptionMode,omitempty"`
	// resourceClaims specifies dynamic resource claims shared by the targeted
	// ReplicatedJobs' pods.
	ResourceClaims []v1alpha3.PodGroupResourceClaim `json:"resourceClaims,omitempty"`
	// jobSchedulingPolicy defines job-level (replica-level) scheduling configuration,
	// where each replica of the targeted ReplicatedJobs forms its own independent gang
	// (i.e. one PodGroup per Job) instead of sharing a single PodGroup across every
	// replica of the targeted ReplicatedJobs. This is part of the Gang-of-Gangs model.
	// When set, targetReplicatedJob must contain exactly one ReplicatedJob name, and
	// the leaf-level schedulingPolicy/schedulingConstraints/disruptionMode/resourceClaims
	// fields on this ReplicatedJobSchedulingPolicy must not be set, since they configure
	// a shared PodGroup that jobSchedulingPolicy replaces with one PodGroup per Job.
	JobSchedulingPolicy *JobSchedulingPolicyApplyConfiguration `json:"jobSchedulingPolicy,omitempty"`
}

// ReplicatedJobSchedulingPolicyApplyConfiguration constructs a declarative configuration of the ReplicatedJobSchedulingPolicy type for use with
// apply.
func ReplicatedJobSchedulingPolicy() *ReplicatedJobSchedulingPolicyApplyConfiguration {
	return &ReplicatedJobSchedulingPolicyApplyConfiguration{}
}

// WithTargetReplicatedJob adds the given value to the TargetReplicatedJob field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetReplicatedJob field.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithTargetReplicatedJob(values ...string) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	for i := range values {
		b.TargetReplicatedJob = append(b.TargetReplicatedJob, values[i])
	}
	return b
}

// WithSchedulingPolicy sets the SchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingPolicy field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithSchedulingPolicy(value v1alpha3.PodGroupSchedulingPolicy) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.SchedulingPolicy = &value
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithSchedulingConstraints(value v1alpha3.PodGroupSchedulingConstraints) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.SchedulingConstraints = &value
	return b
}

// WithDisruptionMode sets the DisruptionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionMode field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithDisruptionMode(value v1alpha3.DisruptionMode) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.DisruptionMode = &value
	return b
}

// WithResourceClaims adds the given value to the ResourceClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceClaims field.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithResourceClaims(values ...v1alpha3.PodGroupResourceClaim) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	for i := range values {
		b.ResourceClaims = append(b.ResourceClaims, values[i])
	}
	return b
}

// WithJobSchedulingPolicy sets the JobSchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobSchedulingPolicy field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithJobSchedulingPolicy(value *JobSchedulingPolicyApplyConfiguration) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.JobSchedulingPolicy = value
	return b
}
