/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha3 "k8s.io/api/scheduling/v1alpha3"
)

// ReplicatedJobSchedulingPolicyApplyConfiguration represents a declarative configuration of the ReplicatedJobSchedulingPolicy type for use
// with apply.
//
// ReplicatedJobSchedulingPolicy targets a named ReplicatedJob with leaf-level
// scheduling configuration.
type ReplicatedJobSchedulingPolicyApplyConfiguration struct {
	// targetReplicatedJob is the name of the ReplicatedJob this policy applies to.
	TargetReplicatedJob *string `json:"targetReplicatedJob,omitempty"`
	// policy defines the leaf-level scheduling policy (basic or gang) for
	// jobs created by this ReplicatedJob.
	// Defaults to Gang when not specified.
	Policy *v1alpha3.PodGroupSchedulingPolicy `json:"policy,omitempty"`
	// constraints defines leaf-level topology constraints for this ReplicatedJob's pods.
	Constraints *v1alpha3.PodGroupSchedulingConstraints `json:"constraints,omitempty"`
	// disruption defines how pods within this ReplicatedJob can be disrupted.
	Disruption *v1alpha3.DisruptionMode `json:"disruption,omitempty"`
	// resourceClaims specifies dynamic resource claims for this ReplicatedJob's pods.
	ResourceClaims []v1alpha3.PodGroupResourceClaim `json:"resourceClaims,omitempty"`
}

// ReplicatedJobSchedulingPolicyApplyConfiguration constructs a declarative configuration of the ReplicatedJobSchedulingPolicy type for use with
// apply.
func ReplicatedJobSchedulingPolicy() *ReplicatedJobSchedulingPolicyApplyConfiguration {
	return &ReplicatedJobSchedulingPolicyApplyConfiguration{}
}

// WithTargetReplicatedJob sets the TargetReplicatedJob field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetReplicatedJob field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithTargetReplicatedJob(value string) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.TargetReplicatedJob = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithPolicy(value v1alpha3.PodGroupSchedulingPolicy) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.Policy = &value
	return b
}

// WithConstraints sets the Constraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Constraints field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithConstraints(value v1alpha3.PodGroupSchedulingConstraints) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.Constraints = &value
	return b
}

// WithDisruption sets the Disruption field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disruption field is set to the value of the last call.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithDisruption(value v1alpha3.DisruptionMode) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	b.Disruption = &value
	return b
}

// WithResourceClaims adds the given value to the ResourceClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceClaims field.
func (b *ReplicatedJobSchedulingPolicyApplyConfiguration) WithResourceClaims(values ...v1alpha3.PodGroupResourceClaim) *ReplicatedJobSchedulingPolicyApplyConfiguration {
	for i := range values {
		b.ResourceClaims = append(b.ResourceClaims, values[i])
	}
	return b
}
