# The following manifests contain a certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: metrics-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/part-of: jobset
    app.kubernetes.io/managed-by: kustomize
  name: metrics-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: system
spec:
  # METRICS_SERVICE_NAME and METRICS_SERVICE_NAMESPACE will be substituted by kustomize
  dnsNames:
    - $(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc
    - $(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc.cluster.local
  commonName: jobset-metrics
  duration: 8760h
  renewBefore: 720h
  usages:
    - server auth
    - client auth
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert # this secret will not be prefixed, since it's not managed by kustomize
