/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/jobset/api/jobset/v1alpha1"
	scheme "sigs.k8s.io/jobset/client-go/clientset/versioned/scheme"
)

// JobSetsGetter has a method to return a JobSetInterface.
// A group's client should implement this interface.
type JobSetsGetter interface {
	JobSets(namespace string) JobSetInterface
}

// JobSetInterface has methods to work with JobSet resources.
type JobSetInterface interface {
	Create(ctx context.Context, jobSet *v1alpha1.JobSet, opts v1.CreateOptions) (*v1alpha1.JobSet, error)
	Update(ctx context.Context, jobSet *v1alpha1.JobSet, opts v1.UpdateOptions) (*v1alpha1.JobSet, error)
	UpdateStatus(ctx context.Context, jobSet *v1alpha1.JobSet, opts v1.UpdateOptions) (*v1alpha1.JobSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.JobSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.JobSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JobSet, err error)
	JobSetExpansion
}

// jobSets implements JobSetInterface
type jobSets struct {
	client rest.Interface
	ns     string
}

// newJobSets returns a JobSets
func newJobSets(c *JobsetV1alpha1Client, namespace string) *jobSets {
	return &jobSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jobSet, and returns the corresponding jobSet object, and an error if there is any.
func (c *jobSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JobSet, err error) {
	result = &v1alpha1.JobSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JobSets that match those selectors.
func (c *jobSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JobSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.JobSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jobSets.
func (c *jobSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jobsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a jobSet and creates it.  Returns the server's representation of the jobSet, and an error, if there is any.
func (c *jobSets) Create(ctx context.Context, jobSet *v1alpha1.JobSet, opts v1.CreateOptions) (result *v1alpha1.JobSet, err error) {
	result = &v1alpha1.JobSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jobsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jobSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a jobSet and updates it. Returns the server's representation of the jobSet, and an error, if there is any.
func (c *jobSets) Update(ctx context.Context, jobSet *v1alpha1.JobSet, opts v1.UpdateOptions) (result *v1alpha1.JobSet, err error) {
	result = &v1alpha1.JobSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobsets").
		Name(jobSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jobSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *jobSets) UpdateStatus(ctx context.Context, jobSet *v1alpha1.JobSet, opts v1.UpdateOptions) (result *v1alpha1.JobSet, err error) {
	result = &v1alpha1.JobSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobsets").
		Name(jobSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jobSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the jobSet and deletes it. Returns an error if one occurs.
func (c *jobSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobsets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jobSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobsets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched jobSet.
func (c *jobSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JobSet, err error) {
	result = &v1alpha1.JobSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jobsets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
