#!/usr/bin/env bash

# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This shell script is used to automatically syncing the Kustomize manifests from manifests templated by trainer Helm chart.
# Run 'make sync-manifests' from the root directory of this repository.

echo "Syncing Kustomize manifests from manifests templated by jobset Helm chart..."

set -o errexit
set -o nounset
set -o pipefail
set -x

# Helm chart release name and namespace.
JOBSET_CHART_DIR=charts/jobset
RELEASE_NAME=${RELEASE_NAME:-jobset}
RELEASE_NAMESPACE=${RELEASE_NAMESPACE:-jobset-system}

# Source directories
SRC_CRD_DIR=config/components/crd/bases

# Destination directories
DST_CRD_DIR=${JOBSET_CHART_DIR}/crds
DST_RBAC_DIR=config/components/rbac
DST_CONTROLLER_DIR=config/components/manager
DST_WEBHOOK_DIR=config/components/webhook
DST_PROMETHEUS_DIR=config/components/prometheus
DST_CERTMANAGER_DIR=config/components/certmanager

MANIFESTS_FILE=$(mktemp)
FIND_EXCLUDE_ARGS="-not -name kustomization.yaml -not -name kustomization.yml"
HELM=${HELM:-helm}
YQ=${YQ:-yq}
YQ_ARGS=".metadata.labels.\"app.kubernetes.io/managed-by\" = \"Kustomize\" | del(.metadata.labels.\"helm.sh/chart\") | ... comments=\"\""

setup() {
    # helm is required to template manifests.
    if ! command -v ${HELM} &>/dev/null; then
        echo "'helm' is not installed, please install it first. Ref: https://helm.sh."
        exit 1
    fi

    # yq is required to parse yaml files.
    if ! command -v ${YQ} &>/dev/null; then
        echo "'yq' is not installed, please install it first. Ref: https://github.com/mikefarah/yq."
        exit 1
    fi

    # Create destination directory if it doesn't exist.
    mkdir -p ${DST_CRD_DIR} ${DST_RBAC_DIR} ${DST_CONTROLLER_DIR} ${DST_WEBHOOK_DIR} ${DST_PROMETHEUS_DIR}

    ${HELM} template ${RELEASE_NAME} ${JOBSET_CHART_DIR} \
        --namespace ${RELEASE_NAMESPACE} \
        --api-versions monitoring.coreos.com/v1/ServiceMonitor \
        --set prometheus.enable=true \
        --set certManager.enable=true > "${MANIFESTS_FILE}"
}

update_crds() {
    # Copy all CRD files to destination directory.
    # shellcheck disable=SC2086
    find ${SRC_CRD_DIR} -type f -name "*.yaml" ${FIND_EXCLUDE_ARGS} -exec cp {} ${DST_CRD_DIR} \;
}

update_rbac() {
    ${YQ} -e "select(.kind == \"ServiceAccount\" and .metadata.name == \"jobset-controller\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_RBAC_DIR}/service_account.yaml

    ${YQ} -e "select(.kind == \"ClusterRole\" and .metadata.name == \"jobset-controller\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_RBAC_DIR}/clusterrole.yaml

    ${YQ} -e "select(.kind == \"ClusterRoleBinding\" and .metadata.name == \"jobset-controller\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_RBAC_DIR}/clusterrole_binding.yaml

    ${YQ} -e "select(.kind == \"Role\" and .metadata.name == \"jobset-controller\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_RBAC_DIR}/role.yaml

    ${YQ} -e "select(.kind == \"RoleBinding\" and .metadata.name == \"jobset-controller\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_RBAC_DIR}/role_binding.yaml
}

update_controller_manager() {
    ${YQ} -e "select(.kind == \"Deployment\" and .metadata.name == \"jobset-controller\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_CONTROLLER_DIR}/deployment.yaml

    ${YQ} -e "select(.kind == \"ConfigMap\" and .metadata.name == \"jobset-controller-config\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_CONTROLLER_DIR}/configmap.yaml
}

update_webhook() {
    # Do not sync webhook secret from Helm chart as it will be generated by Kustomize.
    # ${YQ} -e "select(.kind == \"Secret\" and .metadata.name == \"kubeflow-trainer-webhook-cert\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_WEBHOOK_DIR}/secret.yaml

    ${YQ} -e "select(.kind == \"Service\" and .metadata.name == \"jobset-webhook-service\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_WEBHOOK_DIR}/service.yaml

    ${YQ} -e "select(.kind == \"MutatingWebhookConfiguration\" and .metadata.name == \"jobset-mutating-webhook-configuration\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_WEBHOOK_DIR}/mutating_webhook_configuration.yaml

    ${YQ} -e "select(.kind == \"ValidatingWebhookConfiguration\" and .metadata.name == \"jobset-validating-webhook-configuration\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_WEBHOOK_DIR}/validating_webhook_configuration.yaml
}

update_prometheus() {
    ${YQ} -e "select(.kind == \"Service\" and .metadata.name == \"jobset-metrics-service\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_PROMETHEUS_DIR}/service.yaml

    ${YQ} -e "select(.kind == \"ServiceMonitor\" and .metadata.name == \"jobset-metrics-service-monitor\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_PROMETHEUS_DIR}/service_monitor.yaml
}

update_certmanager() {
    ${YQ} -e "select(.kind == \"Issuer\" and .metadata.name == \"jobset-self-signed-issuer\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_CERTMANAGER_DIR}/issuer.yaml

    ${YQ} -e "select(.kind == \"Certificate\" and .metadata.name == \"jobset-cert\") | ${YQ_ARGS}" "${MANIFESTS_FILE}" > ${DST_CERTMANAGER_DIR}/certificate.yaml
}

cleanup() {
    rm -f "${MANIFESTS_FILE}"
}

setup
update_crds
# Will not sync RBAC from Helm charts, for now we are using Kubebuilder to generate RBAC files.
# update_rbac
update_controller_manager
update_webhook
update_prometheus
update_certmanager
cleanup
