# TODO(k8s 1.35): Once RestartAllContainers is released upstream, this Dockerfile should become the sidecar Dockerfile instead of an example
ARG BUILDER_IMAGE=golang:1.25
ARG BASE_IMAGE=debian:bookworm-slim

# Builder
FROM --platform=${BUILDPLATFORM} ${BUILDER_IMAGE} AS builder

ARG CGO_ENABLED=0
ARG TARGETARCH

WORKDIR /workspace

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the go source
COPY . .

# Build
RUN CGO_ENABLED=${CGO_ENABLED} GOOS=linux GOARCH=${TARGETARCH} go build -a -o bin/in-place-restart-agent cmd/in-place-restart-agent/main.go

# Final image
FROM --platform=${BUILDPLATFORM} ${BASE_IMAGE} AS final

WORKDIR /

# Install ca-certificates
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Copy the binary
COPY --from=builder /workspace/bin/in-place-restart-agent .

# Set the user
USER 65532:65532

# Set the entrypoint
ENTRYPOINT ["/in-place-restart-agent"]
