apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: js
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
spec:
  failurePolicy:
    maxRestarts: 3
    restartStrategy: InPlaceRestart
  replicatedJobs:
  - name: rj
    replicas: 10
    template:
      spec:
        completions: 500
        parallelism: 500
        backoffLimit: 2147483647
        podReplacementPolicy: Failed
        template:
          spec:
            serviceAccountName: jobset-in-place-restart
            restartPolicy: OnFailure
            terminationGracePeriodSeconds: 0
            containers:
            - name: agent
              image: <CHANGE ME>
              env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: IN_PLACE_RESTART_EXIT_CODE
                value: "1"
              # Worker command that exits with the exit code of the file /tmp/exit[0-9]* when it is created
              - name: WORKER_COMMAND
                value: "echo \"Start\"; while sleep 1; do set -- /tmp/exit[0-9]*; [ -f \"\$1\" ] && { n=\${1##*exit}; echo \"exiting \$n\"; exit \"\$n\"; }; done"