/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha2 "sigs.k8s.io/jobset/api/jobset/v1alpha2"
	jobsetv1alpha2 "sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2"
)

// FakeJobSets implements JobSetInterface
type FakeJobSets struct {
	Fake *FakeJobsetV1alpha2
	ns   string
}

var jobsetsResource = v1alpha2.SchemeGroupVersion.WithResource("jobsets")

var jobsetsKind = v1alpha2.SchemeGroupVersion.WithKind("JobSet")

// Get takes name of the jobSet, and returns the corresponding jobSet object, and an error if there is any.
func (c *FakeJobSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.JobSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jobsetsResource, c.ns, name), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}

// List takes label and field selectors, and returns the list of JobSets that match those selectors.
func (c *FakeJobSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.JobSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jobsetsResource, jobsetsKind, c.ns, opts), &v1alpha2.JobSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.JobSetList{ListMeta: obj.(*v1alpha2.JobSetList).ListMeta}
	for _, item := range obj.(*v1alpha2.JobSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jobSets.
func (c *FakeJobSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jobsetsResource, c.ns, opts))

}

// Create takes the representation of a jobSet and creates it.  Returns the server's representation of the jobSet, and an error, if there is any.
func (c *FakeJobSets) Create(ctx context.Context, jobSet *v1alpha2.JobSet, opts v1.CreateOptions) (result *v1alpha2.JobSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jobsetsResource, c.ns, jobSet), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}

// Update takes the representation of a jobSet and updates it. Returns the server's representation of the jobSet, and an error, if there is any.
func (c *FakeJobSets) Update(ctx context.Context, jobSet *v1alpha2.JobSet, opts v1.UpdateOptions) (result *v1alpha2.JobSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jobsetsResource, c.ns, jobSet), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJobSets) UpdateStatus(ctx context.Context, jobSet *v1alpha2.JobSet, opts v1.UpdateOptions) (*v1alpha2.JobSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jobsetsResource, "status", c.ns, jobSet), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}

// Delete takes name of the jobSet and deletes it. Returns an error if one occurs.
func (c *FakeJobSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(jobsetsResource, c.ns, name, opts), &v1alpha2.JobSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJobSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jobsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.JobSetList{})
	return err
}

// Patch applies the patch and returns the patched jobSet.
func (c *FakeJobSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.JobSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobsetsResource, c.ns, name, pt, data, subresources...), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied jobSet.
func (c *FakeJobSets) Apply(ctx context.Context, jobSet *jobsetv1alpha2.JobSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.JobSet, err error) {
	if jobSet == nil {
		return nil, fmt.Errorf("jobSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(jobSet)
	if err != nil {
		return nil, err
	}
	name := jobSet.Name
	if name == nil {
		return nil, fmt.Errorf("jobSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobsetsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeJobSets) ApplyStatus(ctx context.Context, jobSet *jobsetv1alpha2.JobSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.JobSet, err error) {
	if jobSet == nil {
		return nil, fmt.Errorf("jobSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(jobSet)
	if err != nil {
		return nil, err
	}
	name := jobSet.Name
	if name == nil {
		return nil, fmt.Errorf("jobSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobsetsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha2.JobSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.JobSet), err
}
