/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apijobsetv1alpha2 "sigs.k8s.io/jobset/api/jobset/v1alpha2"
	versioned "sigs.k8s.io/jobset/client-go/clientset/versioned"
	internalinterfaces "sigs.k8s.io/jobset/client-go/informers/externalversions/internalinterfaces"
	jobsetv1alpha2 "sigs.k8s.io/jobset/client-go/listers/jobset/v1alpha2"
)

// JobSetInformer provides access to a shared informer and lister for
// JobSets.
type JobSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() jobsetv1alpha2.JobSetLister
}

type jobSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewJobSetInformer constructs a new informer for JobSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewJobSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredJobSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredJobSetInformer constructs a new informer for JobSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredJobSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobsetV1alpha2().JobSets(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobsetV1alpha2().JobSets(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobsetV1alpha2().JobSets(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobsetV1alpha2().JobSets(namespace).Watch(ctx, options)
			},
		},
		&apijobsetv1alpha2.JobSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *jobSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredJobSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *jobSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apijobsetv1alpha2.JobSet{}, f.defaultInformer)
}

func (f *jobSetInformer) Lister() jobsetv1alpha2.JobSetLister {
	return jobsetv1alpha2.NewJobSetLister(f.Informer().GetIndexer())
}
