# Patch for Prometheus ServiceMonitor to enable secure TLS configuration
# using certificates managed by cert-manager
#
# [PROMETHEUS WITH CERTMANAGER]
# ${METRICS_PROMETHEUS_CLIENT_CERT_SECRET_NAME} should be replaced with a prometheus client secret.
# The same certificate for the server ("metrics-server-cert") can potentially be also used for the client.
# It is preferable to use prometheus client certificate if available:
# Either by creating a secret in the jobset controller namespace
# or by using prometheus mounted secret which can be configured via certFile and keyFile in the service_monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: false
        serverName: ${METRICS_SERVICE_NAME}.${METRICS_SERVICE_NAMESPACE}.svc
        ca:
          secret:
            name: metrics-server-cert
            key: ca.crt
        cert:
          secret:
            name: ${METRICS_PROMETHEUS_CLIENT_CERT_SECRET_NAME}
            key: tls.crt
        keySecret:
          name: ${METRICS_PROMETHEUS_CLIENT_CERT_SECRET_NAME}
          key: tls.key
