apiVersion: v1
kind: Service
metadata:
  name: jobset-metrics-service
  namespace: jobset-system
  labels:
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/version: "0.7.3"
    app.kubernetes.io/name: jobset
    app.kubernetes.io/instance: jobset
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jobset
    app.kubernetes.io/instance: jobset
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: 8443
      targetPort: metrics
      protocol: TCP
