apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/part-of: jobset
  name: {{ include "jobset.serviceAccountName" . }}
  namespace: {{.Release.Namespace }}
