{{- if .Values.prometheus.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jobset.fullname" . }}-prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "jobset.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jobset.fullname" . }}-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: '{{ .Values.prometheus.prometheusNamespace }}'
- kind: ServiceAccount
  name: prometheus-operator
  namespace: '{{ .Values.prometheus.prometheusNamespace }}'
{{- end }}
