apiVersion: scheduling.k8s.io/v1beta1
kind: Workload
metadata:
  name: js-delegated
spec:
  controllerRef:
    apiGroup: jobset.x-k8s.io
    kind: JobSet
    name: js-delegated
  podGroupTemplates:
  - name: workers
    schedulingPolicy:
      gang:
        minCount: 2
