apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: per-rj-independent
  namespace: default
spec:
  successPolicy:
    operator: All
  network:
    enableDNSHostnames: true
  scheduling:
    replicatedJobs:
      - targetReplicatedJobs: ["launcher"]
        schedulingPolicy:
          gang: {}
      - targetReplicatedJobs: ["worker"]
        job:
          schedulingPolicy:
            gang: {}
          disruptionMode: 
            all: {}
  replicatedJobs:
    - name: launcher
      replicas: 1
      template:
        spec:
          parallelism: 1
          completions: 1
          completionMode: Indexed
          template:
            spec:
              restartPolicy: OnFailure
              containers:
                - name: launcher
                  image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
                  command: ["sleep", "30s"]
                  resources:
                    requests:
                      cpu: 100m
                      memory: 64Mi
    - name: worker
      replicas: 2
      template:
        spec:
          parallelism: 2
          completions: 2
          completionMode: Indexed
          template:
            spec:
              restartPolicy: OnFailure
              containers:
                - name: worker
                  image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
                  command: ["sleep", "30s"]
                  resources:
                    requests:
                      cpu: 100m
                      memory: 64Mi
