resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: mutating-patch.yaml
  target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
- path: validating-patch.yaml
  target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration