# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from jobset.models.io_k8s_api_scheduling_v1alpha1_pod_group import IoK8sApiSchedulingV1alpha1PodGroup
from jobset.models.io_k8s_api_scheduling_v1alpha1_typed_local_object_reference import IoK8sApiSchedulingV1alpha1TypedLocalObjectReference
from typing import Optional, Set
from typing_extensions import Self

class IoK8sApiSchedulingV1alpha1WorkloadSpec(BaseModel):
    """
    WorkloadSpec defines the desired state of a Workload.
    """ # noqa: E501
    controller_ref: Optional[IoK8sApiSchedulingV1alpha1TypedLocalObjectReference] = Field(default=None, alias="controllerRef")
    pod_groups: List[IoK8sApiSchedulingV1alpha1PodGroup] = Field(description="PodGroups is the list of pod groups that make up the Workload. The maximum number of pod groups is 8. This field is immutable.", alias="podGroups")
    __properties: ClassVar[List[str]] = ["controllerRef", "podGroups"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha1WorkloadSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of controller_ref
        if self.controller_ref:
            _dict['controllerRef'] = self.controller_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in pod_groups (list)
        _items = []
        if self.pod_groups:
            for _item_pod_groups in self.pod_groups:
                if _item_pod_groups:
                    _items.append(_item_pod_groups.to_dict())
            _dict['podGroups'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha1WorkloadSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "controllerRef": IoK8sApiSchedulingV1alpha1TypedLocalObjectReference.from_dict(obj["controllerRef"]) if obj.get("controllerRef") is not None else None,
            "podGroups": [IoK8sApiSchedulingV1alpha1PodGroup.from_dict(_item) for _item in obj["podGroups"]] if obj.get("podGroups") is not None else None
        })
        return _obj


