# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from jobset.models.io_k8s_api_scheduling_v1alpha3_disruption_mode import IoK8sApiSchedulingV1alpha3DisruptionMode
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy
from jobset.models.jobset_v1alpha2_replicated_job_scheduling_policy import JobsetV1alpha2ReplicatedJobSchedulingPolicy
from typing import Optional, Set
from typing_extensions import Self

class JobsetV1alpha2JobSetScheduling(BaseModel):
    """
    JobSetScheduling defines the Workload-Aware Scheduling configuration for a JobSet. All scheduling directives (both global and per-ReplicatedJob) are declared centrally in this struct. Per-ReplicatedJob overrides use the targetReplicatedJob pattern.
    """ # noqa: E501
    constraints: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints] = None
    disruption: Optional[IoK8sApiSchedulingV1alpha3DisruptionMode] = None
    policy: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy] = None
    replicated_job_policies: Optional[List[JobsetV1alpha2ReplicatedJobSchedulingPolicy]] = Field(default=None, description="replicatedJobPolicies specifies per-ReplicatedJob leaf-level scheduling overrides. Each entry targets a named ReplicatedJob.", alias="replicatedJobPolicies")
    __properties: ClassVar[List[str]] = ["constraints", "disruption", "policy", "replicatedJobPolicies"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2JobSetScheduling from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of constraints
        if self.constraints:
            _dict['constraints'] = self.constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of disruption
        if self.disruption:
            _dict['disruption'] = self.disruption.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in replicated_job_policies (list)
        _items = []
        if self.replicated_job_policies:
            for _item_replicated_job_policies in self.replicated_job_policies:
                if _item_replicated_job_policies:
                    _items.append(_item_replicated_job_policies.to_dict())
            _dict['replicatedJobPolicies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2JobSetScheduling from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "constraints": IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints.from_dict(obj["constraints"]) if obj.get("constraints") is not None else None,
            "disruption": IoK8sApiSchedulingV1alpha3DisruptionMode.from_dict(obj["disruption"]) if obj.get("disruption") is not None else None,
            "policy": IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "replicatedJobPolicies": [JobsetV1alpha2ReplicatedJobSchedulingPolicy.from_dict(_item) for _item in obj["replicatedJobPolicies"]] if obj.get("replicatedJobPolicies") is not None else None
        })
        return _obj


