# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API  # noqa: E501

    The version of the OpenAPI document: v0.1.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from jobset.configuration import Configuration


class JobsetV1alpha1ReplicatedJob(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'replicas': 'int',
        'template': 'V1JobTemplateSpec'
    }

    attribute_map = {
        'name': 'name',
        'replicas': 'replicas',
        'template': 'template'
    }

    def __init__(self, name='', replicas=None, template=None, local_vars_configuration=None):  # noqa: E501
        """JobsetV1alpha1ReplicatedJob - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._replicas = None
        self._template = None
        self.discriminator = None

        self.name = name
        if replicas is not None:
            self.replicas = replicas
        self.template = template

    @property
    def name(self):
        """Gets the name of this JobsetV1alpha1ReplicatedJob.  # noqa: E501

        Name is the name of the entry and will be used as a suffix for the Job name.  # noqa: E501

        :return: The name of this JobsetV1alpha1ReplicatedJob.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this JobsetV1alpha1ReplicatedJob.

        Name is the name of the entry and will be used as a suffix for the Job name.  # noqa: E501

        :param name: The name of this JobsetV1alpha1ReplicatedJob.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def replicas(self):
        """Gets the replicas of this JobsetV1alpha1ReplicatedJob.  # noqa: E501

        Replicas is the number of jobs that will be created from this ReplicatedJob's template. Jobs names will be in the format: <jobSet.name>-<spec.replicatedJob.name>-<job-index>  # noqa: E501

        :return: The replicas of this JobsetV1alpha1ReplicatedJob.  # noqa: E501
        :rtype: int
        """
        return self._replicas

    @replicas.setter
    def replicas(self, replicas):
        """Sets the replicas of this JobsetV1alpha1ReplicatedJob.

        Replicas is the number of jobs that will be created from this ReplicatedJob's template. Jobs names will be in the format: <jobSet.name>-<spec.replicatedJob.name>-<job-index>  # noqa: E501

        :param replicas: The replicas of this JobsetV1alpha1ReplicatedJob.  # noqa: E501
        :type: int
        """

        self._replicas = replicas

    @property
    def template(self):
        """Gets the template of this JobsetV1alpha1ReplicatedJob.  # noqa: E501


        :return: The template of this JobsetV1alpha1ReplicatedJob.  # noqa: E501
        :rtype: V1JobTemplateSpec
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this JobsetV1alpha1ReplicatedJob.


        :param template: The template of this JobsetV1alpha1ReplicatedJob.  # noqa: E501
        :type: V1JobTemplateSpec
        """
        if self.local_vars_configuration.client_side_validation and template is None:  # noqa: E501
            raise ValueError("Invalid value for `template`, must not be `None`")  # noqa: E501

        self._template = template

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsetV1alpha1ReplicatedJob):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobsetV1alpha1ReplicatedJob):
            return True

        return self.to_dict() != other.to_dict()
