# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from jobset.models.io_k8s_api_scheduling_v1alpha3_disruption_mode import IoK8sApiSchedulingV1alpha3DisruptionMode
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy
from jobset.models.jobset_v1alpha2_replicated_job_scheduling import JobsetV1alpha2ReplicatedJobScheduling
from typing import Optional, Set
from typing_extensions import Self

class JobsetV1alpha2JobSetScheduling(BaseModel):
    """
    JobSetScheduling defines the Workload-Aware Scheduling configuration for a JobSet. A JobSet must configure scheduling using exactly one of two mutually exclusive models, since composite Gang-of-Gangs PodGroup hierarchies linking a parent PodGroup to leaf PodGroups are not implemented in alpha:   - the top-level (composite) model: set schedulingPolicy, schedulingConstraints,     and/or disruptionMode to configure a single PodGroup (or, under sequenced     startup, one PodGroup per ReplicatedJob) covering the whole JobSet, and leave     replicatedJobs unset.   - the per-ReplicatedJob (leaf) model: set replicatedJobs and leave     schedulingPolicy, schedulingConstraints, and disruptionMode unset at the top     level. Every ReplicatedJob must then be targeted by exactly one     replicatedJobs entry, since there is no top-level policy for an     untargeted ReplicatedJob to fall back to.
    """ # noqa: E501
    disruption_mode: Optional[IoK8sApiSchedulingV1alpha3DisruptionMode] = Field(default=None, alias="disruptionMode")
    replicated_jobs: Optional[List[JobsetV1alpha2ReplicatedJobScheduling]] = Field(default=None, description="replicatedJobs specifies per-ReplicatedJob leaf-level scheduling overrides. Each entry targets one or more named ReplicatedJobs. Mutually exclusive with the top-level schedulingPolicy, schedulingConstraints, and disruptionMode fields: see the type-level comment. When set, every ReplicatedJob in the JobSet must be targeted by exactly one entry.", alias="replicatedJobs")
    scheduling_constraints: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints] = Field(default=None, alias="schedulingConstraints")
    scheduling_policy: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy] = Field(default=None, alias="schedulingPolicy")
    __properties: ClassVar[List[str]] = ["disruptionMode", "replicatedJobs", "schedulingConstraints", "schedulingPolicy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2JobSetScheduling from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disruption_mode
        if self.disruption_mode:
            _dict['disruptionMode'] = self.disruption_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in replicated_jobs (list)
        _items = []
        if self.replicated_jobs:
            for _item_replicated_jobs in self.replicated_jobs:
                if _item_replicated_jobs:
                    _items.append(_item_replicated_jobs.to_dict())
            _dict['replicatedJobs'] = _items
        # override the default output from pydantic by calling `to_dict()` of scheduling_constraints
        if self.scheduling_constraints:
            _dict['schedulingConstraints'] = self.scheduling_constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_policy
        if self.scheduling_policy:
            _dict['schedulingPolicy'] = self.scheduling_policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2JobSetScheduling from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disruptionMode": IoK8sApiSchedulingV1alpha3DisruptionMode.from_dict(obj["disruptionMode"]) if obj.get("disruptionMode") is not None else None,
            "replicatedJobs": [JobsetV1alpha2ReplicatedJobScheduling.from_dict(_item) for _item in obj["replicatedJobs"]] if obj.get("replicatedJobs") is not None else None,
            "schedulingConstraints": IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints.from_dict(obj["schedulingConstraints"]) if obj.get("schedulingConstraints") is not None else None,
            "schedulingPolicy": IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy.from_dict(obj["schedulingPolicy"]) if obj.get("schedulingPolicy") is not None else None
        })
        return _obj


