# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jobset.models.io_k8s_api_scheduling_v1alpha3_workload_composite_pod_group_disruption_mode import IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode
from jobset.models.io_k8s_api_scheduling_v1alpha3_workload_composite_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupSchedulingConstraints
from jobset.models.io_k8s_api_scheduling_v1alpha3_workload_composite_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupSchedulingPolicy
from jobset.models.jobset_v1alpha2_job_scheduling import JobsetV1alpha2JobScheduling
from typing import Optional, Set
from typing_extensions import Self

class JobsetV1alpha2ReplicatedJobScheduling(BaseModel):
    """
    ReplicatedJobScheduling targets one or more named ReplicatedJobs with composite-level scheduling configuration.
    """ # noqa: E501
    disruption_mode: Optional[IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode] = Field(default=None, alias="disruptionMode")
    job: Optional[JobsetV1alpha2JobScheduling] = None
    scheduling_constraints: Optional[IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupSchedulingConstraints] = Field(default=None, alias="schedulingConstraints")
    scheduling_policy: Optional[IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupSchedulingPolicy] = Field(default=None, alias="schedulingPolicy")
    target_replicated_jobs: List[StrictStr] = Field(description="targetReplicatedJobs is the list of ReplicatedJob names this policy applies to. When more than one name is listed, the targeted ReplicatedJobs share a single PodGroup. Every name must be unique across all replicatedJobs entries. The list is limited to a maximum of 50 jobs and the length of each replicatedJobName can not exceed 256 characters.", alias="targetReplicatedJobs")
    __properties: ClassVar[List[str]] = ["disruptionMode", "job", "schedulingConstraints", "schedulingPolicy", "targetReplicatedJobs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2ReplicatedJobScheduling from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disruption_mode
        if self.disruption_mode:
            _dict['disruptionMode'] = self.disruption_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of job
        if self.job:
            _dict['job'] = self.job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_constraints
        if self.scheduling_constraints:
            _dict['schedulingConstraints'] = self.scheduling_constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_policy
        if self.scheduling_policy:
            _dict['schedulingPolicy'] = self.scheduling_policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2ReplicatedJobScheduling from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disruptionMode": IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupDisruptionMode.from_dict(obj["disruptionMode"]) if obj.get("disruptionMode") is not None else None,
            "job": JobsetV1alpha2JobScheduling.from_dict(obj["job"]) if obj.get("job") is not None else None,
            "schedulingConstraints": IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupSchedulingConstraints.from_dict(obj["schedulingConstraints"]) if obj.get("schedulingConstraints") is not None else None,
            "schedulingPolicy": IoK8sApiSchedulingV1alpha3WorkloadCompositePodGroupSchedulingPolicy.from_dict(obj["schedulingPolicy"]) if obj.get("schedulingPolicy") is not None else None,
            "targetReplicatedJobs": obj.get("targetReplicatedJobs")
        })
        return _obj


