# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from jobset.models.io_k8s_api_scheduling_v1alpha3_disruption_mode import IoK8sApiSchedulingV1alpha3DisruptionMode
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_resource_claim import IoK8sApiSchedulingV1alpha3PodGroupResourceClaim
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints
from jobset.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy
from typing import Optional, Set
from typing_extensions import Self

class JobsetV1alpha2JobSchedulingPolicy(BaseModel):
    """
    JobSchedulingPolicy defines scheduling configuration applied at the individual Job (ReplicatedJob replica) level, enabling each replica to be scheduled as its own independent gang. This is part of the Gang-of-Gangs model: the JobSet controller compiles one PodGroupTemplate/PodGroup per Job (replica) of the targeted ReplicatedJob, sized to that Job's own parallelism, rather than one PodGroup shared across all of the ReplicatedJob's replicas.
    """ # noqa: E501
    disruption_mode: Optional[IoK8sApiSchedulingV1alpha3DisruptionMode] = Field(default=None, alias="disruptionMode")
    resource_claims: Optional[List[IoK8sApiSchedulingV1alpha3PodGroupResourceClaim]] = Field(default=None, description="resourceClaims specifies dynamic resource claims shared by the pods of a single replica.", alias="resourceClaims")
    scheduling_constraints: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints] = Field(default=None, alias="schedulingConstraints")
    scheduling_policy: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy] = Field(default=None, alias="schedulingPolicy")
    __properties: ClassVar[List[str]] = ["disruptionMode", "resourceClaims", "schedulingConstraints", "schedulingPolicy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2JobSchedulingPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disruption_mode
        if self.disruption_mode:
            _dict['disruptionMode'] = self.disruption_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in resource_claims (list)
        _items = []
        if self.resource_claims:
            for _item_resource_claims in self.resource_claims:
                if _item_resource_claims:
                    _items.append(_item_resource_claims.to_dict())
            _dict['resourceClaims'] = _items
        # override the default output from pydantic by calling `to_dict()` of scheduling_constraints
        if self.scheduling_constraints:
            _dict['schedulingConstraints'] = self.scheduling_constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_policy
        if self.scheduling_policy:
            _dict['schedulingPolicy'] = self.scheduling_policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2JobSchedulingPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disruptionMode": IoK8sApiSchedulingV1alpha3DisruptionMode.from_dict(obj["disruptionMode"]) if obj.get("disruptionMode") is not None else None,
            "resourceClaims": [IoK8sApiSchedulingV1alpha3PodGroupResourceClaim.from_dict(_item) for _item in obj["resourceClaims"]] if obj.get("resourceClaims") is not None else None,
            "schedulingConstraints": IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints.from_dict(obj["schedulingConstraints"]) if obj.get("schedulingConstraints") is not None else None,
            "schedulingPolicy": IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy.from_dict(obj["schedulingPolicy"]) if obj.get("schedulingPolicy") is not None else None
        })
        return _obj


